language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.11.0+flambda
os:
  - linux
dist:
  - bionic
cache:
  directories:
    - ${HOME}/.opam
before_install:
  - sudo add-apt-repository -y ppa:avsm/ppa; sudo apt update; sudo apt install -y opam
install:
  - travis_wait 40 ./build.sh
  - eval $(opam env)
script:
  - make test
