name: build

on: [push, pull_request]

jobs:
  check:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11.0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libmpfr-dev llvm-12-dev pkg-config libclang-12-dev

      - name: Build Sparrow
        run: |
          ./build.sh || eval $(opam env) && make -j

      - name: Run test (regression)
        run: eval $(opam env) && make test
